baseURL: "https://kastengenharia.github.io/"
theme: "up-business-theme"
languageCode: "pt-br"

title: "KAST"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "KAST Engenharia"
  description: "Nos especializamos em soluções de engenharia focadas em software e hardware."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#FFFFFF"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "Jaraguá do Sul - SC, Brasil"

  contact:
    - "kastengineering.contact@gmail.com"
    - "+55 (47) 99792-5567"
    - "+55 (47) 99250-0637"

  copyright: "© 2024 KAST Engenharia All Rights Reserved"

  copyright: "© 2024 KAST Engenharia, All Rights Reserved"

menus:
  main:
    - name: "Início"
      url: "/#hero"
      weight: 1

    - name: "Sobre Nós"
      url: "/about"
      weight: 2

    - name: "Serviços"
      url: "/services"
      weight: 3
    
  buttons:
    
#     - name: "Our team"
#       url: "/#"
#       weight: 3

#     - name: "Pricing"
#       url: "/#"
#       weight: 4

#     - name: "Blog"
#       url: "/blog"
#       weight: 5

  buttons:
    - name: "Entrar em Contato"
      url: "/contact"
      weight: 5
      pre: "btn btn-primary text-light"

  # footer:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

#     - name: "How we work"
#       url: "/#"
#       weight: 2

#     - name: "Our team"
#       url: "/#"
#       weight: 3

#     - name: "Pricing"
#       url: "/#"
#       weight: 4

#     - name: "Blog"
#       url: "/blog"
#       weight: 5

# taxonomies:
#   series: "series"
#   tags: "tags"
